language: php

php:
   - 5.3
   - 5.5

env:
   global:
      secure: "DvRebaFiq1GvLhsXT4EWM+7bmYcCswvOlE8jUh1Kn77u/mMWL5GPCQjcO7zusdbQyEEROx6yxfKMiGDGysbq55+pJKwpzezwKAaLEhLzlKN1/hge7Tlg27suN2T+LhJsAW94qx9QFv/w0D7Nwg+V5gczrgzvQ++UUmMzc0I+6tI="

before_script:
   - composer self-update
   - sh -c "if $TRAVIS_SECURE_ENV_VARS; then composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN; fi"
   - composer install

script:
   - bin/phpunit
   - bin/phpcs --standard=vendor/apnet/coding-standard/src/Apnet src
